# starship.toml
add_newline = true
command_timeout = 1200

format = """
$directory\
$git_branch$git_status\
$golang\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold cyan"

[git_branch]
format = " [$symbol$branch]($style)"
symbol = " "
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold yellow"
conflicted = "!"
deleted = "✘"
modified = "●"
staged = "✓"
renamed = "»"
untracked = "…"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"

[golang]
format = " [go $symbol $version]($style)"
style = "bold blue"

[cmd_duration]
format = " [took $duration]($style)"
style = "dimmed white"
min_time = 1500

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
